<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>
		TODO 
		, comma 
	</string>
	<key>fileTypes</key>
	<array>
		<string>eprime</string>
		<string>param</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{</string>
	<key>foldingStopMarker</key>
	<string>\}</string>
	<key>name</key>
	<string>Essence'</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(int|bool|matrix|domain)\b</string>
			<key>name</key>
			<string>storage.type.eprime</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(letting|be|indexed|by|of|given|find|maximising|minimising|such|that|max|min|sum|forall|exists|alldifferent|table)\b</string>
			<key>name</key>
			<string>keyword.control.eprime</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;=lex|&gt;=lex|&lt;lex|&gt;lex|=|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
			<key>name</key>
			<string>keyword.operator.comparison.eprime</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(!|=&gt;|&lt;=&gt;|/\\|\\/)</string>
			<key>name</key>
			<string>keyword.operator.logical.eprime</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\-|\+|\*|%|\^|\/)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.eprime</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\$).*$\n?|^language ESSENCE.*\d+\.\d+</string>
			<key>name</key>
			<string>comment.line.number-sign.eprime</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.eprime</string>
	<key>uuid</key>
	<string>E8395FCF-75E8-460A-AC13-3101F56A5B70</string>
</dict>
</plist>
